name: Deploy API to HF Spaces
on:
  push:
    branches: [ main ]
    paths: [ 'serving/**' ]
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install huggingface_hub
      - name: Upload serving/ to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_REPO: ${{ secrets.HF_SPACE_REPO }}
        run: |
          python - <<'PY'
          import os
          from huggingface_hub import HfApi
          api = HfApi(token=os.environ['HF_TOKEN'])
          repo_id = os.environ.get('HF_SPACE_REPO', 'USERNAME/visa-lca-api')
          api.create_repo(repo_id=repo_id, repo_type="space", exist_ok=True, space_sdk="docker")
          api.upload_folder(folder_path="serving", repo_id=repo_id, repo_type="space")
          print("Uploaded to", repo_id)
          PY
